ait/views/chat.py
from flask import render_template, Blueprint
from flask_login import current_user, login_required
from ait import db_fire, socketio
from flask_socketio import send

chat =Blueprint('chat',__name__)

@socketio.on("message")
def sendMessage(message):
    message = current_user.username+ ": " + message
    print(message)
    send(message, broadcast=True)

@chat.route('/chat')
@login_required
def chat_app():
    username = current_user.username
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

    return render_template('chat.html', username = username, user_data = user_data)
    

ait/views/connection.py
from flask import Blueprint, render_template, abort, url_for, redirect, request, flash
from flask_login import current_user, login_required
from ait import db_fire
from datetime import datetime
from ait.models import User

from datetime import date

connect =Blueprint('connection',__name__)

def roleProvider(username):
    # Trial Year static
    year = 2019
    try:
        # passYear =username.split('_')[1][0:2]
        # year =int('20' + passYear)
        currYear = int(date.today().year)

        if (year<currYear-4) :
            return 'Alumini'
        else :
            return 'Student'
    except:
        return None
    


@connect.route('/connection')
@login_required
def connection():
    doc_ref = db_fire.collection('connection').document(current_user.username)
    doc = doc_ref.get()
    type = db_fire.collection('connection').document(current_user.username).get().to_dict()
    print(type)
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    return render_template('connection.html', user_data = user_data, type = type)

@connect.route('/connection/send/<string:username>')
@login_required
def send_req(username):
    if username == current_user.username:
        abort(403)
    else:
        doc_ref =   db_fire.collection('connection').document(current_user.username)
        user_data = db_fire.collection('Alumini').document(username).get().to_dict()
        data = db_fire.collection('connection').document(current_user.username).get()
        
        if data.exists:
            print(data.to_dict())
            temp = data.to_dict()
            if user_data['username'] in data.to_dict().keys():
                print("hello in userdata")
                temp.pop(user_data['username'])
            
            else:    
                temp.update({ 
                    user_data['username'] :{
                    'username' : user_data['username'],
                    'profile_url' : user_data['profile_url'],
                    'created_at' : datetime.utcnow()
                    }
                    })
            db_fire.collection('connection').document(current_user.username).set( temp ,merge = True)
            
        else:
            temp = { 
                user_data['username'] :{
                'username' : user_data['username'],
                'profile_url' : user_data['profile_url'],
                'created_at' : datetime.utcnow()
                }
                }
            doc_ref.set(temp, merge = True)
                
        role = 'Alumini'
        return redirect(url_for('profile.user',username = username, role = role))

@connect.route('/connection/remove/<string:username>')
@login_required
def remove_req(username):
    if username == current_user.username:
        abort(403)
    else:
        data_user = db_fire.collection('connection').document(current_user.username).get().to_dict()
        print(data_user)
        print(type(data_user))
        del data_user[username]
        print(data_user)
        db_fire.collection('connection').document(current_user.username).set( data_user)
        role = 'Alumini'
        return redirect(url_for('profile.user',username = username, role = role))

@connect.route('/connection/<string:type>/<string:username>')
@login_required
def action_req(username,type):
    if username == current_user.username:
        abort(403)
    else:
        doc_ref =   db_fire.collection('connection').document(current_user.username)
        doc = doc_ref.get()

        if doc.exists:
            if type == "accept":
                data = doc.to_dict()['pending']
                data.remove(username)
                
                if 'accept' in doc.to_dict().keys():
                    accept_data = doc.to_dict()['accept']
                    accept_data.connectionend(username)
                else:
                    accept_data = [username]
                
                doc_ref.set({'accept': accept_data},merge = True)
                doc_ref.set({'pending': data},merge = True)

            if type == "reject":
                data = doc.to_dict()['pending']
                data.remove(username)
                doc_ref.set({'pending': data},merge = True)

        return redirect(url_for('home.home_latest'))
    
@connect.route('/search/<string:username>', methods=['GET','POST'])
@login_required
def search_user(username):
        role =roleProvider(username)
        if (role==None):
            flash('Invalid Username.','danger')
            return redirect(url_for('home.home_latest'))
        if username == current_user.username:
            return redirect (url_for('profile.account'))
        else:
            posts = db_fire.collection('post').where('username','==',username).get()
            user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
            profile_data = db_fire.collection(role).document(username).get().to_dict()
            type = db_fire.collection('connection').document(current_user.username).get()
            
            value = False
            
            if type.exists:
                if username in type.to_dict().keys():
                    value = True 
            # print(profile_data)
            return render_template('user.html', profile_data = profile_data,user_data = user_data, posts = posts, value = value  )

ait/views/home.py
from flask import Blueprint, render_template, request
from flask_login import current_user, login_required
from ait import db_fire
from firebase_admin import firestore

home =Blueprint('home',__name__)

@home.route('/')
# @home.route('/home/latest')
# @login_required
# def home_latest():
#     filter1 = request.args.get('branch')
#     filter2 = request.args.get('graduation_year')

#     user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
#     posts = db_fire.collection('post').order_by("date_created", direction=firestore.Query.DESCENDING).get()

#     filtered_posts = []

#     for post in posts:
#         post_data = post.to_dict()
#         post = post_data
#         user_data = db_fire.collection('Alumini').document(post['username']).get().to_dict()
#         # Check filter conditions
#         if filter1 and user_data['branch'] != filter1:
#             continue 
#         if filter2 and user_data['graduation_year'] != filter2:
#             continue 

#         # If post matches the filters, add it to the filtered_posts list
#         filtered_posts.append(post_data)

#     return render_template('home.html', title='Home', user_data=user_data, posts=filtered_posts)

@home.route('/home/latest')
@login_required
def home_latest():
    filter1 = request.args.get('branch')
    filter2 = request.args.get('graduation_year')

    # Get current user's data
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

    posts = db_fire.collection('post').order_by("date_created", direction=firestore.Query.DESCENDING).get()

    filtered_posts = []

    for post in posts:
        post_data = post.to_dict()
        
        # Get the user data of the person who posted the post
        post_user_data = db_fire.collection('Alumini').document(post_data['username']).get().to_dict()
        
        # Check filter conditions
        if filter1 and post_user_data['branch'] != filter1:
            continue 
        if filter2 and post_user_data['graduation_year'] != filter2:
            continue 

        filtered_posts.append(post_data)

    return render_template('home.html', title='Home', user_data=user_data, posts=filtered_posts)



@home.route('/home/top')
@login_required
def home_top():
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    posts = db_fire.collection("post").order_by("likes", direction=firestore.Query.DESCENDING).get()

    return render_template('home_top.html', title = 'Home', user_data = user_data, posts = posts)

@home.route('/home/myPost')
@login_required
def home_myPost():

    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

    posts = db_fire.collection('post').where('username', '==', current_user.username).order_by('date_created', direction=firestore.Query.DESCENDING).get()

    filtered_posts = []

    for post in posts:
        post_data = post.to_dict()

        print(post_data)
        
        if post_data['username'] == current_user.username:
            filtered_posts.append(post_data)

    return render_template('home_myPost.html', title='My Posts', user_data=user_data, posts=filtered_posts)

ait/views/post.py
from flask import Blueprint, render_template, abort, url_for, redirect, jsonify, request, flash
from flask_login import current_user, login_required
from firebase_admin import storage

from ait import db_fire
from ait.forms import PostForm
from ait.views.notification import create_notification

import os
import secrets
from io import BytesIO
from datetime import datetime

post = Blueprint('post', __name__)


@post.route('/get_post')
@login_required
def get_post():
    view_post = render_template('./post/view_post.html')
    data = {'remain': view_post}
    return jsonify(data)


def save_post_media(form_picture, username):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    blob = storage.bucket().blob('post/' + username + '/' + picture_fn)
    file_stream = BytesIO()
    form_picture.save(file_stream)
    blob.upload_from_string(
        file_stream.getvalue(),
        content_type=form_picture.content_type
    )
    blob.make_public()
    print(blob.public_url)

    return blob.public_url


@post.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    if current_user.role != "Alumini":
        abort(403)
    form = PostForm()
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    if form.validate_on_submit():

        data = {"username": current_user.username,
                "title": form.title.data,
                "content": form.content.data,
                "media": '',
                "likes": [],
                "comments": {},
                "date_created": datetime.utcnow(),
                "profile_url": user_data['profile_url'],
                "post_id": current_user.username + datetime.utcnow().strftime(r'%Y%m%d%H%M%S'),
                "role": current_user.role,
                "url": form.url.data,
                "post_type": form.post_type.data  # Saving the post type (Normal or Hiring)
                }
        # print(form.url.data)
        if form.picture.data:
            picture_file = save_post_media(form.picture.data, current_user.username)
            data['media'] = picture_file

        id = current_user.username + data['date_created'].strftime(r'%Y%m%d%H%M%S')
        db_fire.collection('post').document(id).set(data)
        flash('Post Added.', 'success')
        return redirect(url_for('home.home_latest'))
    return render_template('new_post.html', title='New Post', form=form, legend='New Post', user_data=user_data)


@post.route('/post/edit', methods=['GET', 'POST'])
@login_required
def edit_post():
    if current_user.role != "Alumini":
        abort(403)

    form = PostForm()
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

    # Get the post_id from the request args
    post_id = request.args.get('post_id')
    # print("Editing Post-ID:", post_id)

    post_ref = db_fire.collection('post').document(post_id)
    post = post_ref.get().to_dict()

    if not post_id:
        flash('Invalid post ID!', 'danger')
        return redirect(url_for('home.home_latest'))

    # Restrict editing to the post creator
    if post['username'] != current_user.username:
        flash("You are not authorized to edit this post.", "danger")
        abort(403)

    if form.validate_on_submit():

        # print("Form title after submission:", form.title.data)
        # print("Form content after submission:", form.content.data)
        # Prepare the data for updating
        data = {
            "username": current_user.username,
            "title": form.title.data,
            "content": form.content.data,
            "media": '',
            "likes": post.get('likes', []),  # Keep existing likes
            "comments": post.get('comments', {}),  # Keep existing comments
            "date_created": datetime.utcnow(),
            "profile_url": user_data['profile_url'],
            "role": current_user.role,
            "url": form.url.data,
            "post_type": form.post_type.data
        }

        # print("Data being updated:", data)  # Debugging output

        # Update the existing post in Firestore
        try:
            post_ref.update(data)
            flash('Post updated successfully!', 'success')
        except Exception as e:
            print("Error during update:", e)
            flash('An error occurred while updating the post.', 'danger')

        return redirect(url_for('home.home_latest'))

    if post_id:
        # Fetch the existing post from Firestore

        # print("Post Data:", post)

        if not post:
            flash('Post not found!', 'danger')
            return redirect(url_for('home.home_latest'))

        # Populate the form with the existing post data
        form.title.data = post['title']
        form.url.data = post['url']
        form.content.data = post['content']
        form.post_type.data = post['post_type']

    return render_template('edit_post.html', title='Edit Post', form=form, legend='Edit Post', user_data=user_data,
                           post_id=post_id)


@post.route('/delete/<string:post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    # Fetch the post by post_id from the database
    post_ref = db_fire.collection('post').document(str(post_id))
    post = post_ref.get()

    if not post.exists:
        flash('Post not found!', 'danger')
        return redirect(url_for('home.home_latest'))

    post_data = post.to_dict()

    # Check if the current user is the post creator
    if post_data['username'] != current_user.username and current_user.email != 'admin_18185@apsit.edu.in':
        flash('You are not authorized to delete this post', 'danger')
        return redirect(url_for('home.home_latest'))

    try:
        # Admin can delete any post; creator can only delete their own post
        post_ref.delete()

        flash('Post deleted successfully', 'success')
    except Exception as e:
        flash(f'An error occurred while deleting the post: {str(e)}', 'danger')

    return redirect(url_for('home.home_latest'))


@post.route('/comment/<string:post_id>', methods=['POST'])
@login_required
def add_comment(post_id):
    if request.method == "POST":
        username = current_user.username
        date_created = datetime.utcnow()
        comment = request.form.get("comment")
        id = username + date_created.strftime(r'%Y%m%d%H%M%S')
        user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

        data = {
            id: {
                "date_created": date_created,
                "comment": comment,
                "username": current_user.username,
                "profile_url": user_data['profile_url']
            }
        }
        db_fire.collection('post').document(post_id).set({"comments": data}, merge=True)
        flash('Comment Added.', 'success')

        # Notify post owner about the comment
        post_data = db_fire.collection('post').document(post_id).get().to_dict()
        post_owner = post_data.get('username', None)
        if post_owner and post_owner != current_user.username:
            create_notification(post_owner, f"{current_user.username} commented on your post.")

        return redirect(url_for('home.home_latest'))


@post.route('/like/<string:post_id>', methods=['POST'])
@login_required
def like(post_id):
    if request.method == "POST":
        username = current_user.username
        result = db_fire.collection('post').document(post_id).get().to_dict()
        if current_user.username in result['likes']:
            temp = db_fire.collection('post').document(post_id).get().to_dict()['likes']
            temp.remove(current_user.username)
            db_fire.collection('post').document(post_id).set({'likes': temp}, merge=True)

        else:
            result['likes'].append(current_user.username)
            db_fire.collection('post').document(post_id).set(result, merge=True)

            # Notify post owner about the like
            post_owner = result.get('username', None)
            if post_owner and post_owner != current_user.username:
                create_notification(post_owner, f"{current_user.username} liked your post.")

    flash('Post Liked.', 'success')
    return redirect(url_for('home.home_latest'))

ait/templates/layout/auth_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    {% if title %}
    <title>APSIT - {{ title }}</title>
    {% else %}
    <title>APSIT</title>
    {% endif %}

    <meta content="" name="description" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    <link
      href="{{ url_for('static', filename='assets/img/favicon.png') }}"
      rel="icon"
    />
    <link
      href="{{ url_for('static', filename='assets/img/favicon.png') }}assets/img/apple-touch-icon.png"
      rel="apple-touch-icon"
    />

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />

    <!-- Template Main CSS File -->
    <link
      href="{{ url_for('static', filename='assets/css/style.css') }}"
      rel="stylesheet"
    />
  </head>

  <body>
    {% block content %} {% endblock content%}}

    <a
      href="#"
      class="back-to-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <!-- Template Main JS File -->
    <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
  </body>
</html>

ait/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    {% if title %}
    <title>APSIT - {{ title }}</title>
    {% else %}
    <title>APSIT</title>
    {% endif %}

    <meta content="" name="description" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    <link
      href="{{ url_for('static', filename='assets/img/favicon.png') }}"
      rel="icon"
    />
    <link
      href="{{ url_for('static', filename='assets/img/favicon.png') }}assets/img/apple-touch-icon.png"
      rel="apple-touch-icon"
    />

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="{{ url_for('static', filename='assets/vendor/bootstrap-icons/bootstrap-icons.css') }}"
      rel="stylesheet"
    />

    <!-- Template Main CSS File -->
    <link
      href="{{ url_for('static', filename='assets/css/style.css') }}"
      rel="stylesheet"
    />

    <!-- Font Awesome -->
    <script
      src="https://kit.fontawesome.com/998b34ac07.js"
      crossorigin="anonymous"
    ></script>

    <style>
      select.form-select:hover {
        background-color: orange;
        color: white;
      }
    </style>

    <!-- Random-City-Suggetions -->
  </head>

  <body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
      <div class="d-flex align-items-center justify-content-between">
        <a
          href="{{ url_for('home.home_latest') }}"
          class="logo d-flex align-items-center"
        >
          <img
            src="{{ url_for('static',filename='assets/img/logo.png' ) }}"
            alt=""
          />
          <span class="d-none d-lg-block">APSIT</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
      </div>
      <!-- End Logo -->

      <div
        class="search-bar d-flex flex-column flex-md-row align-items-stretch mt-3 mb-3"
      >
        <!-- Search Form -->
        <form
          class="search-form d-flex align-items-center flex-grow-1 mb-2 mb-md-0"
          method="POST"
          action="#"
        >
          <input
            type="text"
            name="query"
            class="search-input"
            style="border-radius: 25px; background-color: #f0f0f0"
            placeholder="Search Username"
            title="Enter search keyword"
          />
          <button type="submit" class="btn btn-primary" title="Search">
            <i class="bi bi-search"></i>
          </button>
        </form>

        <!-- Filter Form -->
        <form
          class="filter-form d-flex flex-column flex-md-row align-items-stretch align-items-md-center ms-md-3 w-100 w-md-auto"
          method="GET"
          action="#"
        >
          <!-- Branch Filter -->
          <select
            name="branch"
            class="form-select mb-2 mb-md-0 me-md-2"
            aria-label="Select Branch"
          >
            <option value="" disabled selected>Branch</option>
            <option value="CSE">CSE</option>
            <option value="IT">IT</option>
            <option value="ECE">ECE</option>
            <option value="Mechanical">Mechanical</option>
            <option value="Civil">Civil</option>
          </select>

          <!-- Graduation Year Filter -->
          <select
            name="graduation_year"
            class="form-select mb-2 mb-md-0 me-md-2"
            aria-label="Select Graduation Year"
          >
            <option value="" disabled selected>Graduation Year</option>
            <option value="2020">2020</option>
            <option value="2021">2021</option>
            <option value="2022">2022</option>
            <option value="2023">2023</option>
            <option value="2024">2024</option>
          </select>

          <!-- Apply Filters Button -->
          <button
            type="submit"
            class="btn btn-primary w-100 w-md-auto"
            style="height: 55px"
          >
            Apply Filters
          </button>
        </form>
      </div>


       <!-- Notification Bell -->
    <div class="position-relative">
      <button id="notificationBell" class="btn btn-light position-relative" onclick="toggleNotificationPopup()">
        <i class="bi bi-bell" style="font-size: 1.5rem;"></i>
        <span id="notificationCount"
          class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
          style="font-size: 0.7rem;">

        </span>
      </button>

      <!-- Notification Popup -->
      <div id="notificationPopup" class="position-absolute top-100 end-0 mt-1 p-3 bg-white shadow rounded d-none"
        style="width: 300px; z-index: 1000;">
        <h6 class="d-flex justify-content-between align-items-center">
          Notifications
          <button class="btn btn-sm btn-outline-primary" onclick="markNotificationsAsRead()">Mark All as Read</button>
        </h6>
        <hr>
        <ul class="list-unstyled" id="notificationList">
          <!-- Notifications will be dynamically populated here -->
        </ul>
      </div>
    </div>





      <!-- End Search Bar -->

      <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
          <li class="nav-item d-block d-lg-none">
            <a class="nav-link nav-icon search-bar-toggle" href="#">
              <i class="bi bi-search"></i>
            </a>
          </li>
          <!-- End Search Icon-->

          <li class="nav-item dropdown pe-3">
            <a
              class="nav-link nav-profile d-flex align-items-center pe-0"
              href="#"
              data-bs-toggle="dropdown"
            >
              {% with profile_url = user_data['profile_url'] %} {% if
              profile_url == '' %}
              <img
                class="rounded-circle me-2"
                src="{{ url_for('static',filename='/profile_pic/default.jpeg' ) }}"
                width="40"
                height="40"
              />
              {% else %}
              <img
                class="rounded-circle me-2"
                src="{{user_data['profile_url']}}"
                width="40"
                height="40"
              />

              {% endif %} {% endwith %}

              <span class="d-none d-md-block dropdown-toggle ps-2"
                >{{user_data['name']}}</span
              > </a
            ><!-- End Profile Iamge Icon -->

            <ul
              class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile"
            >
              <li class="dropdown-header">
                <h6>{{user_data['name']}}</h6>
                <span>{{current_user.role}}</span>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>

              <li>
                <a
                  class="dropdown-item d-flex align-items-center"
                  href="{{url_for('profile.account')}}"
                >
                  <i class="bi bi-person"></i>
                  <span>My Profile</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>

              <li>
                <a
                  class="dropdown-item d-flex align-items-center"
                  href="{{url_for('profile.account')}}"
                >
                  <i class="bi bi-gear"></i>
                  <span>Account Settings</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>

              <!-- <li>
                            <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                                <i class="bi bi-question-circle"></i>
                                <span>Need Help?</span>
                            </a>
                        </li> -->
              <li>
                <hr class="dropdown-divider" />
              </li>

              <li>
                <a
                  class="dropdown-item d-flex align-items-center"
                  href="{{ url_for('authentication.logout') }}"
                >
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Sign Out</span>
                </a>
              </li>
            </ul>
            <!-- End Profile Dropdown Items -->
          </li>
          <!-- End Profile Nav -->
        </ul>
      </nav>
      <!-- End Icons Navigation -->
    </header>
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
      <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('home.home_latest' ) }}">
            <i class="bi bi-grid"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <!-- End Dashboard Nav -->

        {% if current_user.role=='Alumini' %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('post.new_post' ) }}">
            <i class="bi bi-plus-square"></i>
            <span>New Post</span>
          </a>
        </li>
        <!-- End New Post Nav -->
        {% endif %}

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('connection.connection' ) }}">
            <i class="fa-solid fa-user-plus"></i>
            <span>Connection</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('chat.chat_app' ) }}">
            <i class="fa-regular fa-comment me-2"></i>
            <span>Global Chat</span>
          </a>
        </li>

        <li class="nav-item"></li>

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
          <a class="nav-link collapsed" href="{{url_for('profile.account')}}">
            <i class="bi bi-person"></i>
            <span>Profile</span>
          </a>
        </li>
        <!-- End Profile Page Nav -->

        <li class="nav-item">
          <a class="nav-link collapsed" href="https://github.com/SaviPandey">
            <i class="fa-brands fa-github" style="color: #4154f1"></i>
            <span>Source Code</span>
          </a>
        </li>
        <!-- End Profile Page Nav -->

        <!-- End Blank Page Nav -->
      </ul>
    </aside>
    <!-- End Sidebar-->

    {% block content %} {% endblock content%}}

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
      <div class="copyright">
        &copy; Copyright <strong><span>APSIT</span></strong
        >. All Rights Reserved
      </div>
    </footer>
    <!-- End Footer -->

    <a
      href="#"
      class="back-to-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <!-- Vendor JS Files -->
    <script src="{{ url_for('static', filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Template Main JS File -->
    <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/search.js') }}"></script>
  </body>
</html>