ait/views/chat.py
from flask import render_template, Blueprint
from flask_login import current_user, login_required
from ait import db_fire, socketio
from flask_socketio import send

chat =Blueprint('chat',__name__)

@socketio.on("message")
def sendMessage(message):
    message = current_user.username+ ": " + message
    print(message)
    send(message, broadcast=True)

@chat.route('/chat')
@login_required
def chat_app():
    username = current_user.username
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

    return render_template('chat.html', username = username, user_data = user_data)
    

ait/views/connection.py
from flask import Blueprint, render_template, abort, url_for, redirect, request, flash
from flask_login import current_user, login_required
from ait import db_fire
from datetime import datetime
from ait.models import User

from datetime import date

connect =Blueprint('connection',__name__)

def roleProvider(username):
    # Trial Year static
    year = 2019
    try:
        # passYear =username.split('_')[1][0:2]
        # year =int('20' + passYear)
        currYear = int(date.today().year)

        if (year<currYear-4) :
            return 'Alumini'
        else :
            return 'Student'
    except:
        return None
    


@connect.route('/connection')
@login_required
def connection():
    doc_ref = db_fire.collection('connection').document(current_user.username)
    doc = doc_ref.get()
    type = db_fire.collection('connection').document(current_user.username).get().to_dict()
    print(type)
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    return render_template('connection.html', user_data = user_data, type = type)

@connect.route('/connection/send/<string:username>')
@login_required
def send_req(username):
    if username == current_user.username:
        abort(403)
    else:
        doc_ref =   db_fire.collection('connection').document(current_user.username)
        user_data = db_fire.collection('Alumini').document(username).get().to_dict()
        data = db_fire.collection('connection').document(current_user.username).get()
        
        if data.exists:
            print(data.to_dict())
            temp = data.to_dict()
            if user_data['username'] in data.to_dict().keys():
                print("hello in userdata")
                temp.pop(user_data['username'])
            
            else:    
                temp.update({ 
                    user_data['username'] :{
                    'username' : user_data['username'],
                    'profile_url' : user_data['profile_url'],
                    'created_at' : datetime.utcnow()
                    }
                    })
            db_fire.collection('connection').document(current_user.username).set( temp ,merge = True)
            
        else:
            temp = { 
                user_data['username'] :{
                'username' : user_data['username'],
                'profile_url' : user_data['profile_url'],
                'created_at' : datetime.utcnow()
                }
                }
            doc_ref.set(temp, merge = True)
                
        role = 'Alumini'
        return redirect(url_for('profile.user',username = username, role = role))

@connect.route('/connection/remove/<string:username>')
@login_required
def remove_req(username):
    if username == current_user.username:
        abort(403)
    else:
        data_user = db_fire.collection('connection').document(current_user.username).get().to_dict()
        print(data_user)
        print(type(data_user))
        del data_user[username]
        print(data_user)
        db_fire.collection('connection').document(current_user.username).set( data_user)
        role = 'Alumini'
        return redirect(url_for('profile.user',username = username, role = role))

@connect.route('/connection/<string:type>/<string:username>')
@login_required
def action_req(username,type):
    if username == current_user.username:
        abort(403)
    else:
        doc_ref =   db_fire.collection('connection').document(current_user.username)
        doc = doc_ref.get()

        if doc.exists:
            if type == "accept":
                data = doc.to_dict()['pending']
                data.remove(username)
                
                if 'accept' in doc.to_dict().keys():
                    accept_data = doc.to_dict()['accept']
                    accept_data.connectionend(username)
                else:
                    accept_data = [username]
                
                doc_ref.set({'accept': accept_data},merge = True)
                doc_ref.set({'pending': data},merge = True)

            if type == "reject":
                data = doc.to_dict()['pending']
                data.remove(username)
                doc_ref.set({'pending': data},merge = True)

        return redirect(url_for('home.home_latest'))
    
@connect.route('/search/<string:username>', methods=['GET','POST'])
@login_required
def search_user(username):
        role =roleProvider(username)
        if (role==None):
            flash('Invalid Username.','danger')
            return redirect(url_for('home.home_latest'))
        if username == current_user.username:
            return redirect (url_for('profile.account'))
        else:
            posts = db_fire.collection('post').where('username','==',username).get()
            user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
            profile_data = db_fire.collection(role).document(username).get().to_dict()
            type = db_fire.collection('connection').document(current_user.username).get()
            
            value = False
            
            if type.exists:
                if username in type.to_dict().keys():
                    value = True 
            # print(profile_data)
            return render_template('user.html', profile_data = profile_data,user_data = user_data, posts = posts, value = value  )

ait/views/home.py
from flask import Blueprint, render_template, request
from flask_login import current_user, login_required
from ait import db_fire
from firebase_admin import firestore

home =Blueprint('home',__name__)

@home.route('/')
# @home.route('/home/latest')
# @login_required
# def home_latest():
#     filter1 = request.args.get('branch')
#     filter2 = request.args.get('graduation_year')

#     user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
#     posts = db_fire.collection('post').order_by("date_created", direction=firestore.Query.DESCENDING).get()

#     filtered_posts = []

#     for post in posts:
#         post_data = post.to_dict()
#         post = post_data
#         user_data = db_fire.collection('Alumini').document(post['username']).get().to_dict()
#         # Check filter conditions
#         if filter1 and user_data['branch'] != filter1:
#             continue 
#         if filter2 and user_data['graduation_year'] != filter2:
#             continue 

#         # If post matches the filters, add it to the filtered_posts list
#         filtered_posts.append(post_data)

#     return render_template('home.html', title='Home', user_data=user_data, posts=filtered_posts)

@home.route('/home/latest')
@login_required
def home_latest():
    filter1 = request.args.get('branch')
    filter2 = request.args.get('graduation_year')

    # Get current user's data
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

    posts = db_fire.collection('post').order_by("date_created", direction=firestore.Query.DESCENDING).get()

    filtered_posts = []

    for post in posts:
        post_data = post.to_dict()
        
        # Get the user data of the person who posted the post
        post_user_data = db_fire.collection('Alumini').document(post_data['username']).get().to_dict()
        
        # Check filter conditions
        if filter1 and post_user_data['branch'] != filter1:
            continue 
        if filter2 and post_user_data['graduation_year'] != filter2:
            continue 

        filtered_posts.append(post_data)

    return render_template('home.html', title='Home', user_data=user_data, posts=filtered_posts)



@home.route('/home/top')
@login_required
def home_top():
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    posts = db_fire.collection("post").order_by("likes", direction=firestore.Query.DESCENDING).get()

    return render_template('home_top.html', title = 'Home', user_data = user_data, posts = posts)

@home.route('/home/myPost')
@login_required
def home_myPost():

    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

    posts = db_fire.collection('post').where('username', '==', current_user.username).order_by('date_created', direction=firestore.Query.DESCENDING).get()

    filtered_posts = []

    for post in posts:
        post_data = post.to_dict()

        print(post_data)
        
        if post_data['username'] == current_user.username:
            filtered_posts.append(post_data)

    return render_template('home_myPost.html', title='My Posts', user_data=user_data, posts=filtered_posts)

ait/views/post.py
from flask import Blueprint, render_template, abort, url_for, redirect, jsonify, request, flash
from flask_login import current_user, login_required
from firebase_admin import storage

from ait import db_fire
from ait.forms import PostForm
from ait.views.notification import create_notification

import os
import secrets
from io import BytesIO
from datetime import datetime

post = Blueprint('post', __name__)


@post.route('/get_post')
@login_required
def get_post():
    view_post = render_template('./post/view_post.html')
    data = {'remain': view_post}
    return jsonify(data)


def save_post_media(form_picture, username):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    blob = storage.bucket().blob('post/' + username + '/' + picture_fn)
    file_stream = BytesIO()
    form_picture.save(file_stream)
    blob.upload_from_string(
        file_stream.getvalue(),
        content_type=form_picture.content_type
    )
    blob.make_public()
    print(blob.public_url)

    return blob.public_url


@post.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    if current_user.role != "Alumini":
        abort(403)
    form = PostForm()
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    if form.validate_on_submit():

        data = {"username": current_user.username,
                "title": form.title.data,
                "content": form.content.data,
                "media": '',
                "likes": [],
                "comments": {},
                "date_created": datetime.utcnow(),
                "profile_url": user_data['profile_url'],
                "post_id": current_user.username + datetime.utcnow().strftime(r'%Y%m%d%H%M%S'),
                "role": current_user.role,
                "url": form.url.data,
                "post_type": form.post_type.data  # Saving the post type (Normal or Hiring)
                }
        # print(form.url.data)
        if form.picture.data:
            picture_file = save_post_media(form.picture.data, current_user.username)
            data['media'] = picture_file

        id = current_user.username + data['date_created'].strftime(r'%Y%m%d%H%M%S')
        db_fire.collection('post').document(id).set(data)
        flash('Post Added.', 'success')
        return redirect(url_for('home.home_latest'))
    return render_template('new_post.html', title='New Post', form=form, legend='New Post', user_data=user_data)


@post.route('/post/edit', methods=['GET', 'POST'])
@login_required
def edit_post():
    if current_user.role != "Alumini":
        abort(403)

    form = PostForm()
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

    # Get the post_id from the request args
    post_id = request.args.get('post_id')
    # print("Editing Post-ID:", post_id)

    post_ref = db_fire.collection('post').document(post_id)
    post = post_ref.get().to_dict()

    if not post_id:
        flash('Invalid post ID!', 'danger')
        return redirect(url_for('home.home_latest'))

    # Restrict editing to the post creator
    if post['username'] != current_user.username:
        flash("You are not authorized to edit this post.", "danger")
        abort(403)

    if form.validate_on_submit():

        # print("Form title after submission:", form.title.data)
        # print("Form content after submission:", form.content.data)
        # Prepare the data for updating
        data = {
            "username": current_user.username,
            "title": form.title.data,
            "content": form.content.data,
            "media": '',
            "likes": post.get('likes', []),  # Keep existing likes
            "comments": post.get('comments', {}),  # Keep existing comments
            "date_created": datetime.utcnow(),
            "profile_url": user_data['profile_url'],
            "role": current_user.role,
            "url": form.url.data,
            "post_type": form.post_type.data
        }

        # print("Data being updated:", data)  # Debugging output

        # Update the existing post in Firestore
        try:
            post_ref.update(data)
            flash('Post updated successfully!', 'success')
        except Exception as e:
            print("Error during update:", e)
            flash('An error occurred while updating the post.', 'danger')

        return redirect(url_for('home.home_latest'))

    if post_id:
        # Fetch the existing post from Firestore

        # print("Post Data:", post)

        if not post:
            flash('Post not found!', 'danger')
            return redirect(url_for('home.home_latest'))

        # Populate the form with the existing post data
        form.title.data = post['title']
        form.url.data = post['url']
        form.content.data = post['content']
        form.post_type.data = post['post_type']

    return render_template('edit_post.html', title='Edit Post', form=form, legend='Edit Post', user_data=user_data,
                           post_id=post_id)


@post.route('/delete/<string:post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    # Fetch the post by post_id from the database
    post_ref = db_fire.collection('post').document(str(post_id))
    post = post_ref.get()

    if not post.exists:
        flash('Post not found!', 'danger')
        return redirect(url_for('home.home_latest'))

    post_data = post.to_dict()

    # Check if the current user is the post creator
    if post_data['username'] != current_user.username and current_user.email != 'admin_18185@apsit.edu.in':
        flash('You are not authorized to delete this post', 'danger')
        return redirect(url_for('home.home_latest'))

    try:
        # Admin can delete any post; creator can only delete their own post
        post_ref.delete()

        flash('Post deleted successfully', 'success')
    except Exception as e:
        flash(f'An error occurred while deleting the post: {str(e)}', 'danger')

    return redirect(url_for('home.home_latest'))


@post.route('/comment/<string:post_id>', methods=['POST'])
@login_required
def add_comment(post_id):
    if request.method == "POST":
        username = current_user.username
        date_created = datetime.utcnow()
        comment = request.form.get("comment")
        id = username + date_created.strftime(r'%Y%m%d%H%M%S')
        user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

        data = {
            id: {
                "date_created": date_created,
                "comment": comment,
                "username": current_user.username,
                "profile_url": user_data['profile_url']
            }
        }
        db_fire.collection('post').document(post_id).set({"comments": data}, merge=True)
        flash('Comment Added.', 'success')

        # Notify post owner about the comment
        post_data = db_fire.collection('post').document(post_id).get().to_dict()
        post_owner = post_data.get('username', None)
        if post_owner and post_owner != current_user.username:
            create_notification(post_owner, f"{current_user.username} commented on your post.")

        return redirect(url_for('home.home_latest'))


@post.route('/like/<string:post_id>', methods=['POST'])
@login_required
def like(post_id):
    if request.method == "POST":
        username = current_user.username
        result = db_fire.collection('post').document(post_id).get().to_dict()
        if current_user.username in result['likes']:
            temp = db_fire.collection('post').document(post_id).get().to_dict()['likes']
            temp.remove(current_user.username)
            db_fire.collection('post').document(post_id).set({'likes': temp}, merge=True)

        else:
            result['likes'].append(current_user.username)
            db_fire.collection('post').document(post_id).set(result, merge=True)

            # Notify post owner about the like
            post_owner = result.get('username', None)
            if post_owner and post_owner != current_user.username:
                create_notification(post_owner, f"{current_user.username} liked your post.")

    flash('Post Liked.', 'success')
    return redirect(url_for('home.home_latest'))

ait/templates/edit_post.html
{% extends './layout/base.html' %}
{% block content %}

<main id="main" class="main">

    <!-- Page Title -->
    <div class="pagetitle">
        <h1>Dashboard</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('home.home_latest' ) }}">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-8">
                <div class="row">
                    <!-- View Post-->
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <!-- Create post box start -->
                                <div class="d-flex flex-column comment-section">
                                    <div class="bg-light p-2">
                                        <div class="d-flex flex-row align-items-start">
                                            {% with profile_url = user_data['profile_url'] %}
                                            {% if profile_url == '' %}
                                            <img class="rounded-circle me-2" style="aspect-ratio: 1;"
                                                src="{{ url_for('static',filename='/profile_pic/default.jpeg' ) }}" height="40" width="40">
                                            {% else %}
                                            <img class="rounded-circle me-2" style="aspect-ratio: 1;"
                                                src="{{user_data['profile_url']}}" height="40" width="40">

                                            {% endif %}
                                            {% endwith %}

                                            <h5 class="card-title">{{user_data['name']}}
                                                <span>/{{user_data['role']}}</span>
                                            </h5>

                                        </div>

                                        <!-- Add Post Type Badge here -->
                                        {% if post_type == 'hiring' %}
                                        <span class="badge badge-success">Hiring Post</span>
                                        {% else %}
                                        <span class="badge badge-primary">Normal Post</span>
                                        {% endif %}

                                        <form method="POST" action="{{ url_for('post.edit_post', post_id=post_id) }}" enctype="multipart/form-data">
                                            {{ form.hidden_tag() }}
                                            <fieldset class="form-group">
                                                <legend class="border-bottom mb-4">{{ legend }}</legend>

                                                <!-- Title Field -->
                                                <div class="form-group">
                                                    {{ form.title.label(class="form-control-label") }}
                                                    {% if form.title.errors %}
                                                    {{ form.title(class="form-control form-control-lg
                                                    is-invalid") }}
                                                    <div class="invalid-feedback">
                                                        {% for error in form.title.errors %}
                                                        <span>{{ error }}</span>
                                                        {% endfor %}
                                                    </div>
                                                    {% else %}
                                                    {{ form.title(class="form-control form-control-lg") }}
                                                    {% endif %}
                                                </div>

                                                <!-- Post Type Field (Normal / Hiring) -->
                                                <div class="form-group">
                                                    {{ form.post_type.label }}
                                                    {{ form.post_type(class="form-control") }}
                                                </div>

                                                <!-- URL Field -->
                                                <div class="form-group">
                                                    {{ form.url.label(class="form-control-label") }}
                                                    {% if form.url.errors %}
                                                    {{ form.url(class="form-control form-control-lg
                                                    is-invalid") }}
                                                    <div class="invalid-feedback">
                                                        {% for error in form.url.errors %}
                                                        <span>{{ error }}</span>
                                                        {% endfor %}
                                                    </div>
                                                    {% else %}
                                                    {{ form.url(class="form-control form-control-lg") }}
                                                    {% endif %}
                                                </div>

                            
                                                 <!-- Content Field -->
                                                <div class="form-group">
                                                    {{ form.content.label(class="form-control-label") }}
                                                    {% if form.content.errors %}
                                                    {{ form.content(class="form-control form-control-lg
                                                    is-invalid") }}
                                                    <div class="invalid-feedback">
                                                        {% for error in form.content.errors %}
                                                        <span>{{ error }}</span>
                                                        {% endfor %}
                                                    </div>
                                                    {% else %}
                                                    {{ form.content(class="form-control form-control-lg") }}
                                                    {% endif %}
                                                </div>

                                                <!-- Picture Upload -->
                                                <div class="mb-3 mt-3">
                                                    {{ form.picture.label() }}
                                                    {{ form.picture(class="form-control-file") }}
                                                    {% if form.picture.errors %}
                                                    {% for error in form.picture.errors %}
                                                    <span class="text-danger">{{ error }}</span></br>
                                                    {% endfor %}
                                                    {% endif %}
                                                </div>
                                                <!-- file input ends -->

                                            </fieldset>

                                            <!-- Submit Button -->
                                            <div class="form-group">
                                                {{ form.submit(class="btn btn-outline-info") }}
                                            </div>

                                        </form>
                                    </div>
                                </div>
                                <!-- Create box ends -->

                            </div>
                        </div>
                    </div><!-- End Create Post -->



                </div>
            </div><!-- End Left side columns -->

            <!-- Right side columns -->
            <div class="col-lg-4">
                <!-- News & Updates Traffic -->
                <div class="card">
                    <div class="filter">
                        <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                            <li class="dropdown-header text-start">
                                <h6>Filter</h6>
                            </li>

                            <li><a class="dropdown-item" href="#">Today</a></li>
                            <li><a class="dropdown-item" href="#">This Month</a></li>
                            <li><a class="dropdown-item" href="#">This Year</a></li>
                        </ul>
                    </div>

                    <div class="card-body pb-0">
                        <h6 class="card-title">News &amp; Updates <span>| Today</span></h6>
                        <div class="post-item clearfix">
                          <h6><a href="https://www.apsit.edu.in/">APSIT Student Makes DTE Web Portal </a></h6>
                          <p>We are thrilled to announce a significant achievement by our talented APSIT students! The NBA Status Portal, a groundbreaking project developed for the Maharashtra Government, showcases the innovative spirit and technical prowess of our students....</p>
                        </div>
                        <div class="post-item clearfix">
                          <h6><a href="https://www.apsit.edu.in/">
                                🏆 Congratulations to Our Thane Smart City Hackathon and Start-up Pitch Fest Winners! 🏆 
                              </a>
                          </h6>
                          <p>🚦 Priority Based Traffic Manipulation (Safety & Security):
                            Winners: Arun Mathai & Atharva Sunil Dhamankar (SE Comps)
                            ♻️ E-waste Management using Blockchain (Solid Waste Management):
                              Winners: Anuj Mishra & Ishan Sathe (BE Comps).....
                          </p>
                        </div>
                        <div class="post-item clearfix">
                          <h6><a
                              href="https://www.apsit.edu.in/">APSIT Teams Win 1st Prize in Smart India Hackathon 2023.</a></h6>
                          <p>APSIT celebrates as two teams clinch the top prize of Rs. 1 Lakh each in the 2023 Smart India Hackathon, hosted by the Government of India. The victory showcases APSIT's innovation and technological excellence...</p>
                        </div>
                        <div class="post-item clearfix">
                          <h6><a href="https://www.apsit.edu.in/">Alumni
                              Success Stories (Saurabh)-Nativsouls</a></h6>
                          <p>To help artisans and craftsmen who are constantly duped by middlemen and big corporate houses led to
                            formation of Nativsouls...</p>
                        </div>
                        <div class="post-item clearfix">
                          <h6><a href="https://www.apsit.edu.in/">🎉 Congratulations to Our International Placement Achievers! 🎉</a></h6>
                          <p>A. P. Shah Institute of Technology, Thane is elated to announce that our talented B.E. students from the Batch of 2023-24 have achieved exceptional international placements at JTP Co. Ltd.!👏 Heartiest congratulations to: Harmit Saini
                            Devanshu Mahapatra
                            Akshaykumar Jain
                            Siddharth Singh...</p>
                        </div>
            
                      </div><!-- End sidebar recent posts-->

                </div>
            </div><!-- End News & Updates -->

        </div><!-- End Right side columns -->

        </div>
    </section>

</main><!-- End #main -->

<!-- home js starts -->
<script src="{{ url_for('static', filename = 'assets/js/home.js' ) }}"></script>
{% endblock content%}}

ait/templates/test.html
<h1>Hello World</h1>